plugins {
    id 'java'
}

group = 'example.gradle'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.telegram:telegrambots-longpolling:9.5.0'
    implementation 'org.telegram:telegrambots-client:9.5.0'

    implementation 'org.apache.commons:commons-csv:1.9.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}